---
title: "Interactive charts"
description: "A collection of my visualizations. Some of them are based on popular challenges such as #TidyTuesday and #30DayMapChallenge. The collection is not restricted to those, as I find from time to time interesting datasets to work with."
link-external-newwindow: true
page-layout: full
comments: false
title-block-banner: true
execute:
  echo: false
  warning: false
---

## 30 Day Chart Challenge

### Soil Phosphorus Levels

```{r}
#| echo: false
library(tidyverse)
library(sf)
library(sp)
library(mapview)
library(leaflet)
library(RColorBrewer)
```


```{r}
#| echo: false
#| warning: false
#| message: false

# Read in Geo-nutrition soil data
soil_data <- read.csv("data/data.csv", header = TRUE)

# Filter a few columns
sub_soil <- soil_data %>% 
  dplyr::select(ID, Latitude, Longitude, Altitude, P_Olsen)

# Rename columns
names(sub_soil) <- c("ID", "Latitude", "Longitude", "Altitude", "Phosphorus")

# Remove rows with NA values
sub_soil_na <- na.omit(sub_soil)

# Check if process was successful
invisible(sum(is.na(sub_soil_na)))

# Create sf object
soil_sf <- st_as_sf(sub_soil, coords = c("Longitude", "Latitude"), crs = 4326)

# Method 1: Using as() from methods package
soil_sp <- as(soil_sf, "Spatial")

# Method 2 (older sf versions): as_Spatial()
# soil_sp <- as_Spatial(soil_sf)

# Check the result
invisible(class(soil_sp))

# Populate pop-ups
my_pops <- paste0("<strong>ID: </strong>", soil_sp$ID,
"<br>\n <strong> Phosphorus mg/kg: </strong>",
soil_sp$Phosphorus)

# Colour ramp
pal1 <- colorNumeric("YlOrBr", domain = soil_sp$Phosphorus)

# Create interactive map
leaflet() %>%
  addProviderTiles("Esri.WorldImagery") %>%
  addCircleMarkers(data = soil_sp, 
                   radius = 4,
                   color = ~pal1(Phosphorus),
                   stroke = TRUE,
                   weight = 1,
                   fillOpacity = 0.8,
                   popup = my_pops) %>%
  addLegend("bottomright", 
            pal = pal1,
            values = soil_sp$Phosphorus, 
            title = "Soil Phosphorus mg/kg",
            opacity = 0.8)
```